---
swagger: "2.0"
info:
  version: "0.1"
  title: MS-Template
tags:
- name: AuthService
consumes:
- application/json
produces:
- application/json
paths:
  /v1/auth/login:
    post:
      tags:
      - AuthService
      summary: Takes user input to generate a token.
      operationId: AuthService_Login
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/authLoginRequest'
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/authLoginResponse'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
definitions:
  authLoginRequest:
    type: object
    required:
    - password
    - username
    properties:
      username:
        type: string
        title: Required. The username of user
      password:
        type: string
        title: Required. The password of user
    description: |-
      The request message for the auth.AuthService\Login
      method.
  authLoginResponse:
    type: object
    properties:
      accessToken:
        type: string
    description: |-
      The response message for the auth.AuthService\Login
      method.
  protobufAny:
    type: object
    properties:
      typeUrl:
        type: string
      value:
        type: string
        format: byte
        pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          $ref: '#/definitions/protobufAny'
