name: Template CI

on:
  push:
    branches: 
    - main
  pull_request:
    branches: 
    - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -installsuffix cgo -ldflags="-w -s" -o ms-server ./cmd/ms-project
      
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
        
    - name: Run unit tests
      env: 
        DB_USERNAME: '${{ secrets.MONGODB_USERNAME }}'
        DB_PASSOWRD: '${{ secrets.MONGODB_PASSWORD }}'
        DB_CLUSTER: '${{ secrets.MONGODB_CLUSTER }}' 
        
      run: go test -v --shuffle=on ./...
      
    - name: Run server coverage
      run: go test ./server/... -coverprofile=coverage.txt -covermode=atomic
      
